# Generated by Django 6.0.3 on 2026-03-27 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_verificationcode'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verificationcode',
            table='verification_codes',
        ),
    ]
