"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
from django.templatetags.static import static

# Load .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'pamoja-rides.onrender.com', 
    'localhost', 
    '127.0.0.1',
    '.onrender.com'
]

MOMO_BASE_URL = os.environ.get('MOMO_BASE_URL', 'https://sandbox.momodeveloper.mtn.com')
MOMO_TARGET_ENVIRONMENT = os.environ.get('MOMO_TARGET_ENVIRONMENT', 'sandbox')
MOMO_COLLECTION_SUBSCRIPTION_KEY = os.environ.get('MOMO_COLLECTION_SUBSCRIPTION_KEY', '')
MOMO_API_USER = os.environ.get('MOMO_API_USER', '')
MOMO_API_KEY = os.environ.get('MOMO_API_KEY', '')
MOMO_CALLBACK_URL = os.environ.get('MOMO_CALLBACK_URL', '')
BOOKING_FEE_RWF = int(os.environ.get('BOOKING_FEE_RWF', 500))

# Disbursements (payouts to drivers / refunds to passengers).
# MTN MoMo treats Collections and Disbursements as separate API products,
# each with their own subscription key + API user/key pair.
MOMO_DISBURSEMENT_SUBSCRIPTION_KEY = os.environ.get('MOMO_DISBURSEMENT_SUBSCRIPTION_KEY', '')
MOMO_DISBURSEMENT_API_USER = os.environ.get('MOMO_DISBURSEMENT_API_USER', '')
MOMO_DISBURSEMENT_API_KEY = os.environ.get('MOMO_DISBURSEMENT_API_KEY', '')

# Escrow-lite: fraction of the fare (not the service fee) Pamoja keeps as
# commission when releasing funds to the driver.
COMMISSION_RATE = float(os.environ.get('COMMISSION_RATE', '0.10'))

# When true, MomoClient/MomoDisbursementClient skip real network calls and
# auto-approve everything — lets escrow-lite be tested end-to-end without
# working MoMo sandbox credentials. Defaults to on in DEBUG, off otherwise.
# Set MOMO_SIMULATE=False explicitly once real MoMo creds are verified working.
MOMO_SIMULATE = os.environ.get('MOMO_SIMULATE', 'True' if DEBUG else 'False') == 'True'

# Explicit opt-in to unlock SimulatePaymentSuccessView outside of DEBUG.
# Off by default even in production — set ALLOW_SIMULATE=True on the
# backend service's env vars only while you deliberately want the
# "Simulate Payment" button to work against production. Turn back off
# once real MoMo creds are wired up.
ALLOW_SIMULATE = os.environ.get('ALLOW_SIMULATE', 'False') == 'True'


# Application definition

INSTALLED_APPS = [
    # Unfold must come before django.contrib.admin
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "daphne",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "channels",
    "users",
    "rides",
    "notifications",
    "payments",
]

UNFOLD = {
    "SITE_TITLE": "Pamoja Rides",
    "SITE_HEADER": "Pamoja Rides Admin",
    "SITE_URL": "/",
    "SITE_ICON": None,
    "SITE_LOGO": lambda request: static("admin/img/logo.svg"),
    "SITE_SYMBOL": "directions_car",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "COLORS": {
        "primary": {
            "50": "239 246 255",
            "100": "219 234 254",
            "200": "191 219 254",
            "300": "147 197 253",
            "400": "96 165 250",
            "500": "59 130 246",
            "600": "37 99 235",
            "700": "29 78 216",
            "800": "30 64 175",
            "900": "30 58 138",
            "950": "23 37 84",
        },
    },
    "TABS": [
        {
            "models": ["users.user", "rides.driverprofile"],
            "items": [
                {"title": "All Users", "icon": "group", "link": "/admin/users/user/"},
                {"title": "Driver Profiles", "icon": "badge", "link": "/admin/rides/driverprofile/"},
            ],
        },
        {
            "models": ["rides.ride", "rides.booking", "rides.ridestop"],
            "items": [
                {"title": "All Rides", "icon": "directions_car", "link": "/admin/rides/ride/"},
                {"title": "Bookings", "icon": "confirmation_number", "link": "/admin/rides/booking/"},
            ],
        },
    ],
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Dashboard",
                "separator": False,
                "items": [
                    {
                        "title": "Overview",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "Users",
                "separator": True,
                "items": [
                    {
                        "title": "All Users",
                        "icon": "group",
                        "link": "/admin/users/user/",
                        "badge": "core.admin.user_count",
                    },
                    {
                        "title": "Driver Profiles",
                        "icon": "badge",
                        "link": "/admin/rides/driverprofile/",
                        "badge": "core.admin.driver_count",
                    },
                    {
                        "title": "Flagged Identities",
                        "icon": "flag",
                        "link": "/admin/rides/driverprofile/?identity_flag__exact=1",
                    },
                ],
            },
            {
                "title": "Rides",
                "separator": True,
                "items": [
                    {
                        "title": "Active Rides",
                        "icon": "directions_car",
                        "link": "/admin/rides/ride/?status__exact=active",
                    },
                    {
                        "title": "All Rides",
                        "icon": "list",
                        "link": "/admin/rides/ride/",
                    },
                    {
                        "title": "Bookings",
                        "icon": "confirmation_number",
                        "link": "/admin/rides/booking/",
                    },
                ],
            },
            {
                "title": "Notifications",
                "separator": True,
                "items": [
                    {
                        "title": "Notifications",
                        "icon": "notifications",
                        "link": "/admin/notifications/notification/",
                    },
                ],
            },
        ],
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "https://pamoja-rides-client.onrender.com",
    "https://pamoja-ride.com",
    "https://www.pamoja-ride.com",
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'core.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [os.getenv('REDIS_URL', 'redis://127.0.0.1:6379')],
        },
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv('DATABASE_URL')
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# 1. This is where collectstatic will PUT all your files
STATIC_ROOT = BASE_DIR / "staticfiles"

# 2. These are extra places Django looks for static files (like your custom CSS)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 3. Use WhiteNoise to serve static files on Render (highly recommended)
if not DEBUG:
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

AUTHENTICATION_BACKENDS = [
    'users.universal_login.UniversalAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'users.authentication.RawJWTAuthentication',
    ],
}

AUTH_USER_MODEL = 'users.User'