# Generated by Django 6.0.5 on 2026-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ride_booked', 'Ride Booked'), ('ride_full', 'Ride Full'), ('ride_edited', 'Ride Edited'), ('booking_confirmed', 'Booking Confirmed'), ('ride_cancelled', 'Ride Cancelled'), ('fare_released', 'Fare Released'), ('no_show_refund', 'No-show Refund')], max_length=30),
        ),
    ]
