# Generated by Django 6.0.4 on 2026-04-26 12:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_ride_price_per_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('district', models.CharField(blank=True, max_length=255)),
                ('province', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
            options={
                'db_table': 'locations',
            },
        ),
        migrations.AlterField(
            model_name='ride',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
