# Generated by Django 6.0.4 on 2026-04-27 07:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_location_alter_ride_price_per_seat'),
    ]

    operations = [
        migrations.CreateModel(
            name='RideStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('order', models.PositiveIntegerField()),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='rides.ride')),
            ],
            options={
                'db_table': 'ride_stops',
                'ordering': ['order'],
            },
        ),
    ]
