# Generated by Django 6.0.4 on 2026-04-27 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_ridestop'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='destination_lng',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='origin_lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='origin_lng',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
    ]
