# Generated by Django 6.0.4 on 2026-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0005_ride_destination_lat_ride_destination_lng_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='origin_lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='origin_lng',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
