# Generated by Django 6.0.4 on 2026-04-29 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0007_alter_ride_destination_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='destination_lng',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='origin_lat',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='origin_lng',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_lat',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_lng',
            field=models.DecimalField(blank=True, decimal_places=50, max_digits=100, null=True),
        ),
    ]
