# Generated by Django 6.0.4 on 2026-05-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0011_alter_ride_destination_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='ai_confidence',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='ai_license_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='ai_nid_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='ai_verified_same_person',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='identity_flag',
            field=models.BooleanField(default=False, help_text='Flagged for admin review due to identity mismatch.'),
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='identity_flag_reason',
            field=models.TextField(blank=True, help_text='Explanation of why this profile was flagged.'),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='license_image_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='nid_image_url',
            field=models.URLField(max_length=500),
        ),
    ]
