# Generated by Django 6.0.5 on 2026-06-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0012_driverprofile_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='arrived_at_destination',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ridestop',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
