# Generated by Django 6.0.5 on 2026-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0013_ride_arrived_at_destination_ridestop_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='no_show_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times passengers reported this driver as a no-show.'),
        ),
    ]
