# Generated by Django 6.0.5 on 2026-08-12 12:59

import rides.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0014_driverprofile_no_show_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pickup_code',
            field=models.CharField(default=rides.models.generate_pickup_code, max_length=4),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
