# Generated by Django 6.0.5 on 2026-08-18 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0015_booking_pickup_code_booking_pickup_confirmed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number collected on the driver permit form. Used as a fallback MoMo payout number when the user has none on their account.', max_length=20),
        ),
    ]
