# Generated by Django 6.0.5 on 2026-07-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='disbursement_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='disbursement_reference',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='disbursement_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='driver_payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='escrow_status',
            field=models.CharField(choices=[('none', 'None'), ('locked', 'Locked'), ('released', 'Released'), ('refunded', 'Refunded')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='fare_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='no_show_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_reference',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_status',
            field=models.CharField(blank=True, choices=[('', 'None'), ('pending', 'Pending'), ('successful', 'Successful'), ('failed', 'Failed')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='service_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
