# Generated by Django 6.0.5 on 2026-08-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_commission_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='arrival_confirmation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
